language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  include:
    - rust: 1.15.1
      env: DOWNGRADE=1
script: |
  if [[ -n $DOWNGRADE ]]; then
    cargo generate-lockfile
    cargo update --package rand --precise 0.3.10
  fi
  cargo build --verbose
  cargo test --verbose